#!/bin/bash

if [ -d /sys/kernel/mm/ksm ] && [ $(cat /sys/kernel/mm/ksm/run) == "1" ];
then
  echo '<<<ksm>>>'
  for i in pages_sharing pages_shared
  do
    echo ${i}=$(cat /sys/kernel/mm/ksm/$i)
  done
fi